databases:
  - name: diabetesmanagement
    plan: free
    databaseName: diabetesmanagement
    user: diabetesmanagement

services:
  - type: web
    name: diabetesmanagement
    plan: free
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: diabetesmanagement
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
